/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project2;

import bitcamp.project2.util.Menu;

public class App {
    public static void main(String[] args) {

        Menu m = Menu.getInstance();
        m.menu();

    }
}
