/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project2;

import bitcamp.project2.util.Membership;
import bitcamp.project2.controller.PlanController;
import bitcamp.project2.controller.UserController;
import bitcamp.project2.util.Prompt;

public class App {

    UserController userController = new UserController();
    PlanController planController = new PlanController();

    public static void main(String[] args) {

        Membership m = Membership.getInstance();
        m.menu();
    }
}
